#!/bin/bash

echo "Load Rocket & Run Default Simulation"
echo "Test Case 1: No *.ork File Given"
./rockettalk.py
echo
echo "Test Case 2: Specified *.ork File Not Found"
./rockettalk.py badFileName.ork
echo
echo "Test Case 3: Specified *.ork File Does not Contain Simulations"
./rockettalk.py noSimulations.ork
echo
echo "Test Case 4: File Found and Contains Simulations"
./rockettalk.py asimple.ork
echo 
echo "Specify Host"
echo "Test Case 1: Invalid Host Given"
./rockettalk.py asimple.ork -fc "badHost"
echo
echo "Test Case 2: Valid Host Given"
./rockettalk.py asimple.ork -fc "localhost"
echo
echo "Test Case 3: No Entry after the -fc Flag"
./rockettalk.py asimple.ork -fc
echo
echo "Run Specified Simulation"
echo "Test Case 1: Input is not an Integer"
./rockettalk.py asimple.ork -s notInteger
echo
echo "Test Case 2: Input is Less Than One"
./rockettalk.py "asimple.ork" -s 0
echo
echo "Test Case 3: Invalid Simulation Index Value"
./rockettalk.py "asimple.ork" -s 6
echo
echo "Test Case 4: Simulation is Outdated"
./rockettalk.py outDatedSimulation.ork
echo
echo "Test Case 5: Simulation Found"
echo "Lower Boundary Value"
./rockettalk.py asimple.ork -s 1
echo
echo "Upper Boundary Value"
./rockettalk.py asimple.ork -s 5
echo
echo "Test Case 6: No Entry after the -s Flag"
./rockettalk.py asimple.ork -s
echo
echo "Real Time"
echo "Test Case 1: Test Real Time Simulation"
./rockettalk.py asimple.ork -rt
echo

